# Generated by Django 5.1.1 on 2025-11-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('room_type', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('suite', 'Suite'), ('deluxe', 'Deluxe Room'), ('family', 'Family Room')], max_length=20)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.PositiveIntegerField(help_text='Number of people')),
                ('description', models.TextField(blank=True)),
                ('room_image', models.ImageField(blank=True, null=True, upload_to='room_images/')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
