# Generated by Django 5.1.1 on 2025-11-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
        migrations.AddField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('dirty', 'Dirty'), ('maintenance', 'Maintenance')], default='available', max_length=20),
        ),
    ]
