# Generated by Django 5.1.1 on 2025-11-30 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_fooditem_foodorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='chef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_orders', to='accounts.employee'),
        ),
    ]
