# Generated by Django 6.0.5 on 2026-06-13 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_booking_is_paid_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='Global Trust Bank', max_length=100)),
                ('account_holder_name', models.CharField(default='Grand Hotel Pvt Ltd', max_length=100)),
                ('account_number', models.CharField(default='1029384756', max_length=40)),
                ('ifsc_code', models.CharField(blank=True, default='GTBL0001234', max_length=20)),
                ('branch', models.CharField(blank=True, default='Main Branch', max_length=100)),
                ('payment_link', models.URLField(blank=True, help_text='Optional online payment link.', null=True)),
                ('instructions', models.TextField(blank=True, default='Please transfer the total booking amount to the account above and upload your payment receipt.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Setting',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_file', models.FileField(upload_to='payment_receipts/')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='accounts.booking')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
