# Generated by Django 6.0.5 on 2026-06-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_branch_sitesetting_booking_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipient_role',
            field=models.CharField(blank=True, choices=[('receptionist', 'Reception'), ('kitchen', 'Kitchen'), ('bar', 'Bar'), ('housekeeping', 'Housekeeping'), ('manager', 'Manager'), ('admin', 'Admin / Front Office')], max_length=20),
        ),
    ]
