# Generated by Django 6.0.5 on 2026-06-16 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_message_recipient_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Purchase/cost price used for profit calculation.', max_digits=8),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hotel_address',
            field=models.TextField(blank=True, default='123 Luxury Ave, Hotel City'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hotel_email',
            field=models.EmailField(blank=True, default='contact@grandhotel.com', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hotel_logo',
            field=models.ImageField(blank=True, help_text='Logo shown on the website, dashboard and invoices.', null=True, upload_to='hotel/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hotel_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient_role',
            field=models.CharField(blank=True, choices=[('receptionist', 'Reception'), ('kitchen', 'Kitchen'), ('bar', 'Bar'), ('housekeeping', 'Housekeeping'), ('manager', 'Manager'), ('admin', 'Admin / Front Office'), ('guest', 'Guests')], max_length=20),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('salary', 'Staff Salaries'), ('repairs', 'Hotel Repairs / Maintenance'), ('electricity', 'Electricity Bill'), ('water', 'Water Bill'), ('supplies', 'Supplies / Inventory Purchase'), ('marketing', 'Marketing'), ('rent', 'Rent / Lease'), ('other', 'Other')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('spent_on', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='accounts.branch')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-spent_on', '-id'],
            },
        ),
    ]
