# Generated by Django 6.0.5 on 2026-06-17 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_drink_cost_price_sitesetting_hotel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo shown in the navbar, dashboard and invoices for this branch.', null=True, upload_to='branch_logos/'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_items', to='accounts.branch'),
        ),
    ]
