# Generated by Django 6.0.5 on 2026-06-24 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_assign_default_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Used for product expiration alerts.', null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Alert when stock falls to or below this level.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_body',
            field=models.TextField(blank=True, default='Our hotel started with a simple vision: to create a sanctuary of peace and luxury for travelers.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_heading',
            field=models.CharField(blank=True, default='A Legacy of Luxury', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_hero_subtitle',
            field=models.TextField(blank=True, default='Redefining luxury and hospitality. Experience world-class comfort in the heart of the city.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_hero_title',
            field=models.CharField(blank=True, default='About Us', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_map_embed',
            field=models.TextField(blank=True, help_text='Google Maps embed link (the src URL of the iframe) for the hotel location.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='home_hero_image',
            field=models.ImageField(blank=True, help_text='Background image for the homepage hero section.', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='home_hero_subtitle',
            field=models.TextField(blank=True, default='Experience luxury, comfort, and world-class service. Book your perfect getaway today.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='home_hero_title',
            field=models.CharField(blank=True, default='Welcome to Grand Hotel', max_length=150),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Litre'), ('ml', 'Millilitre'), ('pcs', 'Pieces'), ('pack', 'Pack'), ('dozen', 'Dozen')], default='pcs', max_length=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per unit (for accounting).', max_digits=10)),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('low_stock_threshold', models.DecimalField(decimal_places=2, default=5, help_text='Alert when stock falls to or below this level.', max_digits=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='accounts.branch')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngredientStockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Positive for restock, negative for usage/adjustment', max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='accounts.ingredient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LaundryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laundry_orders', to='accounts.booking')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laundry_orders', to='accounts.branch')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laundry_orders', to='accounts.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LaundryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('wash', 'Wash'), ('iron', 'Iron'), ('starch', 'Starch'), ('dryclean', 'Dry Clean'), ('sewing', 'Sewing'), ('fold', 'Fold & Pack')], default='wash', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost to the hotel (for profit calculation).', max_digits=8)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laundry_services', to='accounts.branch')),
            ],
            options={
                'ordering': ['service_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LaundryOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.laundryorder')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.laundryservice')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('bar_expiry', 'Bar Product Expiration'), ('low_stock', 'Low Stock / Restock Due'), ('new_booking', 'New Guest Booking'), ('cancel_booking', 'Cancelled Booking'), ('new_message', 'New Message'), ('new_kitchen_order', 'New Kitchen Order'), ('new_bar_order', 'New Bar Order'), ('new_laundry_order', 'New Laundry Order')], max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('body', models.CharField(blank=True, max_length=255)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/')),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='accounts.room')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
