# Generated by Django 6.0.5 on 2026-06-25 06:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_drink_expiry_date_drink_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_type',
            field=models.CharField(choices=[('receptionist', 'Receptionist'), ('kitchen', 'Kitchen Staff'), ('housekeeping', 'Housekeeping'), ('bar', 'Bar Staff'), ('manager', 'Manager'), ('spa', 'Spa Therapist')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('bar_expiry', 'Bar Product Expiration'), ('low_stock', 'Low Stock / Restock Due'), ('new_booking', 'New Guest Booking'), ('cancel_booking', 'Cancelled Booking'), ('new_message', 'New Message'), ('new_kitchen_order', 'New Kitchen Order'), ('new_bar_order', 'New Bar Order'), ('new_laundry_order', 'New Laundry Order'), ('new_spa_order', 'New Spa Order'), ('wallet_topup', 'Wallet Top-up Receipt')], max_length=30),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('status', 'Status Change'), ('payment', 'Payment'), ('login', 'Login'), ('logout', 'Logout'), ('other', 'Other')], default='other', max_length=20)),
                ('module', models.CharField(help_text='e.g. Booking, Drink, Ingredient, LaundryOrder.', max_length=50)),
                ('summary', models.CharField(max_length=255)),
                ('object_repr', models.CharField(blank=True, max_length=120)),
                ('object_id', models.CharField(blank=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.branch')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IngredientUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text="How much was used (in the ingredient's unit).", max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, help_text='Cost per unit at the time of usage (for accounting).', max_digits=10)),
                ('note', models.CharField(blank=True, help_text='e.g. dish / meal it was used for.', max_length=255)),
                ('used_on', models.DateField(default=django.utils.timezone.now, help_text='The date the ingredient was used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_usages', to='accounts.branch')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='accounts.ingredient')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SpaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('appointment_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spa_orders', to='accounts.booking')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spa_orders', to='accounts.branch')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spa_orders', to='accounts.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpaService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('massage', 'Massage'), ('facial', 'Facial'), ('body', 'Body Treatment'), ('manicure', 'Manicure / Pedicure'), ('sauna', 'Sauna / Steam'), ('package', 'Spa Package'), ('other', 'Other')], default='massage', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Estimated duration in minutes.')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, help_text='Therapist cost / supplies (for profit calc).', max_digits=8)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='spa_images/')),
                ('is_available', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spa_services', to='accounts.branch')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpaOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.spaorder')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.spaservice')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTopUpReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_file', models.FileField(upload_to='wallet_topups/')),
                ('note', models.CharField(blank=True, help_text='Bank reference / transaction ID', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_topups_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_topups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
