# Generated by Django 6.0.5 on 2026-06-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_employee_job_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='assigned_branches',
            field=models.ManyToManyField(blank=True, help_text='Branches a manager is allowed to view and switch between.', related_name='managers', to='accounts.branch'),
        ),
    ]
