# Generated by Django 6.0.5 on 2026-07-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_employee_assigned_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='pay_account_holder_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='pay_account_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='branch',
            name='pay_bank_branch',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bank branch'),
        ),
        migrations.AddField(
            model_name='branch',
            name='pay_bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='pay_ifsc_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='IFSC / SWIFT code'),
        ),
        migrations.AddField(
            model_name='branch',
            name='pay_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='pay_link',
            field=models.URLField(blank=True, help_text='Optional online payment link.', null=True),
        ),
    ]
